# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4319135722c779d4d22589bf2a759fae619b22b89f1b556776d4a34b4e38d33327064644827099864e6bc4fbd9e626445ce5ab575ffe49a9098675baee7680e7

test:
  secret_key_base: 15ad23479dc146994c093cb53abb6cacb9d6358c895fb5b1461bb8120621dcbcded1bf14342a7045b6c5a700d6793e7fcf4b1be62ef1f95fed6f46285731e468

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
